---
title: "Getting started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse)
library(avoncap)
```

```{r setup}

# The data input directory on my development machine:
options("avoncap.input" = "~/Data/avoncap/")

# library(avoncap)
devtools::load_all()

```

# Input data location

* first level directories.
* Filenames need some indication of database year (either as 20-21,21-22,... or as y1,y2,...)

```{r}
# The data input directory on my development machine:
options("avoncap.input" = "~/Data/avoncap/")

# The directory structure:
fs::dir_tree(path = avoncap::input(),glob="*/cache/*",invert=TRUE)
```


```{r}
# get the most recent files
avoncap::most_recent_files("ethnicity")
```


```{r}
# devtools::load_all()
try(avoncap::load_data("missing"))
```

# Load data sources and recording provenance

```{r}
ethn = avoncap::load_data("ethnicity")
avoncap::most_recent_files("nhs-extract","deltave")
rawData = avoncap::load_data("nhs-extract","deltave")
# rawData = avoncap::load_data("nhs-extract","deltave",merge = FALSE)
avoncap::save_data_source_info(ethn, rawData, .file = tempfile("file-info",fileext = ".txt"))
```

# Normalising data 

```{r}
# devtools::install_local(force=TRUE)
normData = rawData %>% 
  avoncap::validate_data() %T>%
  # note the magrittr `T` pipe above to drop the output of write issues
  avoncap::write_issues("issues.csv") %>%
  avoncap::normalise_data()
```

# Mapping columns

```{r}
# Successfully mapped columns
# attr(normData,"mapped")

# Columns that are present in the normData but not mapped
attr(normData,"unmapped")

# Columns not present in the normData for which mapping rules were supplied
attr(normData,"missing")
```

# Original field names, and labels.

```{r}
# devtools::load_all()

# generate a set of readable label mappings from column to printable name for the whole normData set
# overriding a particular label
# readable_label_mapping(normData, demog.age="TEST")

# Map a single column name as a string to a readable label
readable_label("comorbid.previous_MI")

# get mapping from original field names pre-normalisation to
# post normalisation fields
original_field_names(normData)

```



```{r}
# unname(readable_label_mapping(normData))
```

# Augmenting the VE extract data

```{r}
# devtools::load_all()
augData = normData %>% avoncap::augment_data()
```

# loading and normalising the central database

```{r}
rawData2 = avoncap::load_data("avoncap-export","central", merge=TRUE)
# without merge: currently: INCONSISTENT COLUMN(S) IN FILES: sars_cov2_antigen
# due to the fact it is mostly a numeric but some values ">250"

# devtools::load_all()

failures = rawData2 %>% avoncap::validate_data()  %>% avoncap::write_issues("~/avoncap-issues")

normData2 = rawData2 %>% avoncap::normalise_data()

tmp = failures %>% 
    filter(.error_type %in% c("none checked in checkbox","missing value")) %>%
    filter(!.variable %in% c("consented","ppc","include_patient","hosp")) %>% 
    inner_join(rawData2, by="record_number", suffix=c("",".raw")) %>%
  group_by(.variable) %>%
  filter(n()>20)
  
if (nrow(tmp) != 0) {  
  ggplot(tmp, aes(x=enrollment_date, fill=as.factor(hosp)))+
    geom_histogram(binwidth = 7)+
    scale_x_date(date_breaks = "1 month", date_labels = "%m-%Y")+
    theme(axis.text.x.bottom = element_text(angle = 90, vjust=0.5, hjust=1))+
    facet_wrap(~.variable,scales = "free_y")
} else {
  message("No quality checked variables with more than 20 missing items (excluding consent flags)")
}

```

```{r}
normMicro = rawData2 %>% normalise_data(instrument = "micro")

normMicro %>% filter(micro.test_performed=="yes") %>% select(micro.pathogen) %>% unnest(micro.pathogen) %>% with(table(pathogen,detected,  useNA = "always"))
normMicro %>% filter(micro.test_performed=="yes") %>% select(micro.test_type, micro.pathogen) %>% unnest(micro.pathogen) %>% filter(detected=="yes") %>% group_by(pathogen, micro.test_type) %>%
  count() %>% arrange(desc(n))

```


```{r}
normVirol = rawData2 %>% normalise_data(instrument = "virol")

normVirol  %>% filter(virol.test_performed=="yes") %>% select(virol.pathogen) %>% unnest(virol.pathogen) %>% with(table(pathogen,detected,  useNA = "always"))
normVirol %>% filter(virol.test_performed=="yes") %>% select(virol.test_type, virol.pathogen) %>% unnest(virol.pathogen) %>% filter(detected=="yes") %>% 
  # with(table(pathogen, virol.test_type,  useNA = "always")) %>% 
  group_by(pathogen, virol.test_type) %>%
  count() %>% arrange(desc(n))
  

```


```{r}
normRadio = rawData2 %>% normalise_data(instrument = "radio")

# old format tmp3  %>% filter(radio.test_performed=="yes") %>% with(table(radio.test_type, radio.lung_malignancy))
normRadio %>% filter(radio.test_performed=="yes") %>% select(radio.alrtd_finding) %>% unnest(radio.alrtd_finding) %>% with(table(finding,present,  useNA = "always"))
normRadio %>% filter(radio.test_performed=="yes") %>% select(radio.test_type, radio.non_alrtd_finding) %>% unnest(radio.non_alrtd_finding) %>% filter(present=="yes") %>% with(table(finding, radio.test_type,  useNA = "always"))

```

```{r}
normHaem = rawData2 %>% normalise_data(instrument = "haem") 
augHaem = normHaem %>% augment_data()

augHaem %>% xglimpse(haem.troponin_level, haem.d_dimer_level)
augHaem %>% xglimpse(haem.crp_level, haem.white_cell_count_level)

# x = augHaem %>% summary()
# t(x)
```


# Augmenting the central database



```{r}
# devtools::load_all()
augData2 = normData2 %>% avoncap::augment_data()

augData2 %>% xglimpse(admission.category,  admission.presentation_3_class)
augData2 %>% xglimpse(admission.covid_pcr_result,  admission.presentation_3_class)
augData2 %>% xglimpse(admission.infective_cause,  admission.presentation_3_class)
augData2 %>% xglimpse(admission.infective_cause,  admission.is_covid)

augData2 %>% xglimpse(admin.consent_withheld, admission.presentation_3_class)
augData2 %>% xglimpse(admin.consent_withheld, admin.catchment_status)

augData2 %>% xglimpse(admin.consented, admin.catchment_status)
```




