---
title: "Quality assurance"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quality assurance}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(tidyverse)
library(avoncap)
```

```{r setup}

if (!rlang::is_installed("avoncap")) devtools::load_all()

# The data input directory on my development machine:
options("avoncap.input" = "~/Data/avoncap/")

# library(avoncap)
devtools::load_all()

```

# loading and normalising the central database

```{r}
rawData = avoncap::load_data("avoncap-export","central", merge=FALSE)
rawData2 = avoncap::load_data("avoncap-export","central", merge=TRUE)

# devtools::load_all()
rawData3 = rawData2 %>% avoncap::validate_data() 
normData2 = rawData3 %>% avoncap::normalise_data()
failures = rawData3 %>% avoncap::write_issues("~/avoncap-issues")
```

```{r}
tmp = failures %>% 
    filter(.error_type %in% c("none checked in checkbox","missing value")) %>% 
    inner_join(rawData2, by="record_number", suffix=c("",".raw")) %>%
    group_by(.variable) %>%
    filter(
      !is.na(enrollment_date) &
      !is.na(hosp)
    ) %>%
    filter(
      n()>20
    )

if (nrow(tmp) > 0) {
  ggplot(tmp, aes(x=enrollment_date, fill=as.factor(hosp)))+
    geom_histogram(binwidth = 7)+
    scale_x_date(date_breaks = "1 month", date_labels = "%m-%Y")+
    theme(axis.text.x.bottom = element_text(angle = 90, vjust=0.5, hjust=1))+
    facet_wrap(~.variable,scales = "free_y")
} else {
  message("No systematically missing values in checked items")
}
```


```{r}

# normData2 = rawData2 %>% 
#   avoncap::normalise_data(.nocache = TRUE)

augData2 = normData2 %>% avoncap::augment_data()
avoncap::find_new_field_names(normData2, "adm_diagnosis")

```
